---
- hosts: all
  pre_tasks:
    - name: Update cache for Debian-based distros
      apt:
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'
      changed_when: false

    - ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: yes
        sysctl_file: /etc/sysctl.d/ip_forward.conf

- hosts: vpn_home
  roles:
    - ansible-role-fail2ban
    - githubixx.ansible_role_wireguard
