---
- hosts: vpn.robinopletal.com
  vars_files:
    - "vars/credentials.yml"
    - "vars/main.yml"
  pre_tasks:
    - name: Update cache for Debian-based distros
      apt:
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'
      changed_when: false

    - name: Manage authorized SSH keys
      authorized_key:
        exclusive: yes
        user: root
        key: "{{ item }}"
      with_file: "{{ ansible_public_keys_path }}"

    - ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: yes
        sysctl_file: /etc/sysctl.d/ip_forward.conf

    - name: Include tasks for monitoring
      include_tasks: tasks/monitoring.yml
      tags: setup-monitoring

  roles:
    - ansible-role-fail2ban

- hosts: vpn_home
  roles:
    - githubixx.ansible_role_wireguard
